export { default as Swith } from './Switch.vue'
export { default as Button } from './Button.vue'
export { default as Tabs } from './Tabs.vue'
export { default as Tab } from './Tab.vue'
export { openDialog } from './openDialog'
